//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSix.selfie {
	
	
	public partial class index {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl header_img;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl selfi_list;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl sel_list;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl avai_list;
		
		protected System.Web.UI.WebControls.Content Content3;
	}
}
