//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSix.tour {
	
	
	public partial class index {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl header_img;
		
		protected System.Web.UI.WebControls.TextBox txt_EMAIL;
		
		protected System.Web.UI.WebControls.DropDownList ddl_CITY;
		
		protected System.Web.UI.HtmlControls.HtmlInputButton btn_Save_Menu;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl prefer_list;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl tour_img;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl tour_list;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl voting_list;
		
		protected System.Web.UI.WebControls.Content Content3;
	}
}
